# Generated by Django 3.0.8 on 2020-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45)),
                ("title", models.CharField(max_length=45)),
                ("sub_title", models.CharField(max_length=45)),
                ("active", models.SmallIntegerField()),
            ],
        ),
    ]
