# Generated by Django 3.0.8 on 2020-08-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200816_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='label',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='order',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
