# Generated by Django 3.0.8 on 2020-08-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200816_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='vignette_alt',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt',
            field=models.CharField(default='', max_length=45),
        ),
    ]
