# Generated by Django 3.0.8 on 2020-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200816_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontent',
            name='color_setting',
            field=models.CharField(default='#c8c9ca', max_length=10),
        ),
    ]
