# Generated by Django 3.0.8 on 2020-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_projectcontent_color_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='path',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='vignette_path',
            field=models.CharField(max_length=100),
        ),
    ]
