# Generated by Django 3.0.8 on 2020-08-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200817_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgalerie',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
